### ISSUE TITLE
Error: Docker build failed with exit code 1

### ISSUE THREAD

**Issue by WebKenth** [stefanzweifel/laravel-phpinsights-action#4]
Build container for action use: '/home/runner/work/_actions/stefanzweifel/laravel-phpinsights-action/v1.1.1/Dockerfile'.
Error: Docker build failed with exit code 1

```bash
#7 [2/3] RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
  #7 0.1[66](https://github.com/Maulund/Maulund/actions/runs/8935386470/job/24543893961#step:2:66) fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
  #7 ERROR: process "/bin/sh -c apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv" did not complete successfully: exit code: 139
  ------
   > [2/3] RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv:
  0.166 fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
  ------
  Dockerfile:14
  --------------------
    12 |     # fix work iconv library with alphine
    13 |     # https://github.com/nunomaduro/phpinsights/issues/43#issuecomment-498108857
    14 | >>> RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
    15 |     ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
    16 |     
  --------------------
  ERROR: failed to solve: process "/bin/sh -c apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv" did not complete successfully: exit code: 139
  Warning: Docker build failed with exit code 1, back off 5.541 seconds before retry.
```

I am fairly new to github actions and i've only just added this as a test. NO clue why a simple apk add should fail at this stage

This is my github actions workflow yaml file:

```yml
name: PHP Insights
on: push
jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - uses: php-actions/composer@v6
      with:
        dev: no
        interaction: no
        php_version: 8.3.4
        version: 2.6.3

    - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
```

**Comment by stefanzweifel** [comment]
Thanks for reporting!

As you might have noticed, this Action is quite old and the last change has been made 4 years ago.
(Personally, I don't use this action or phpinsights anymore. That's why this Action has been semi abandoned)

One cause for this issue could be that it uses PHP 7.4 under the hood. https://github.com/stefanzweifel/laravel-phpinsights-action/blob/master/Dockerfile#L1

---

As you already install the composer dependencies anyway, I would suggest you don't use this Action, but call `php artisan insights` directly. 
That's also all the Action [does](https://github.com/stefanzweifel/laravel-phpinsights-action/blob/master/entrypoint.sh) anyway.

You're workflow would then look like this.

```diff
name: PHP Insights
on: push
jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - uses: php-actions/composer@v6
      with:
        dev: no
        interaction: no
        php_version: 8.3.4
        version: 2.6.3

+   - name: Run phpinsights
+     run: php artisan insights -n
-   - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
```

If you want to make the workflow even shorter, you could use the https://github.com/ramsey/composer-install Action, that handles caching and installing composer dependencies for you.

```yml
name: PHP Insights
on: push
jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.3.4"

    - uses: "ramsey/composer-install@v3"

    - name: Run phpinsights
      run: php artisan insights -n
```

---

As mentioned, I don't use this Action anymore. And as you demonstrated, it also doesn't work anymore. Will de-list the Action and will archive this repository soon.
